version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      # - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=marcowinar@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    restart: always
      
  web:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: winarmarco/zentodo-web:prod
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`chatkinator.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: ZenTodo
    secret:
      - db_root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

secrets:
  db_root_password:
    file: db_root_password.txt

volumes:
  mysql-volume:
    driver: local
  letsencrypt: